=== Silentsky0/wai-project-comic-books/src/web/static/xml/komiksy_schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xs:element name="comics">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="heroes" type="heroesType"/>
				<xs:element name="origin" type="originType"/>
				<xs:element name="formats" type="formatsType"/>
				<xs:element name="specialties" type="specialtiesType"/>
				<xs:element name="ages" type="agesType"/>
				<xs:element name="favourites" type="favouritesType"/>
				<xs:element name="sources" type="sourcesType"/>
			</xs:sequence>
			<xs:attribute name="language">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[a-zA-z]{2}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	
	<xs:complexType name="heroesType">
		<xs:sequence>
			<xs:element name="hero" type="heroType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="heroType">
		<xs:sequence>
			<xs:group ref="heroGroup"/>
			<xs:element name="introduction" type="introductionType"/>
		</xs:sequence>
		<xs:attribute ref="brand"/>
	</xs:complexType>

	<xs:group name="heroGroup">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="superpower" type="xs:string"/>
			<xs:element name="image" type="linkType"/>
		</xs:sequence>		
	</xs:group>

	<xs:complexType name="introductionType">
		<xs:sequence>
			<xs:element name="date" type="introductionDateType"/>
			<xs:element ref="age"/>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="introductionDateType">
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-zA-Z])* [0-9]{4}"/>
		</xs:restriction>
	</xs:simpleType>


	<xs:complexType name="originType">
		<xs:sequence>
			<xs:element name="country" type="countryType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="countryType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="term" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="origin" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="english"/>
					<xs:enumeration value="non-english"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>


	<xs:complexType name="formatsType">
		<xs:sequence>
			<xs:element name="format" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="most-popular" type="xs:string"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="specialtiesType">
		<xs:sequence>
			<xs:element name="writer" type="specialtyType"/>
			<xs:element name="artist" type="specialtyType"/>
			<xs:element name="letterer" type="specialtyType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="specialtyType">
		<xs:sequence>
			<xs:element name="job" type="xs:string"/>
			<xs:element name="difficulty">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="agesType">
		<xs:sequence>
			<xs:element ref="age" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	


	<xs:complexType name="favouritesType">
		<xs:choice>
			<xs:element name="comic" type="comicType"/>
			<xs:element name="collection">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="author" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:choice>
		<xs:attribute name="title">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="20"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute ref="brand"/>
	</xs:complexType>

	<xs:complexType name="comicType">
		<xs:sequence>
			<xs:element name="issues">
				<xs:simpleType>
					<xs:restriction>
						<xs:simpleType>
							<xs:list>
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="0"/>
										<xs:maxExclusive value="1000"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:list>
						</xs:simpleType>
						<xs:maxLength value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="author" type="xs:string"/>
		</xs:sequence>
		<xs:attributeGroup ref="comicAttrGroup"/>
	</xs:complexType>

	<xs:attributeGroup name ="comicAttrGroup">
		<xs:attribute name="title" type="xs:string"/>
		<xs:attribute ref="brand"/>
		<xs:attribute name="id" type="xs:byte"/>
	</xs:attributeGroup>
	

	<xs:complexType name="sourcesType" mixed="true">
		<xs:sequence>
			<xs:element name="link" type="linkType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	
	
	<xs:complexType name="linkType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="source" type="xs:anyURI"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>



	<xs:element name="age" type="ageType"/>
	<xs:complexType name="ageType" mixed="true">
		<xs:sequence>
			<xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="duration" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[0-9]{4} - [0-9]{4}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:attribute name="brand" type="brandType"/>
	<xs:simpleType name="brandType">
		<xs:union memberTypes="brandShort brandLong"/>
	</xs:simpleType>
	<xs:simpleType name="brandShort">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Marvel"/>
			<xs:enumeration value="DC"/>
			<xs:enumeration value="Vertigo"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="brandLong">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Marvel Comics"/>
			<xs:enumeration value="DC Comics"/>
			<xs:enumeration value="Vertigo Comics"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== Silentsky0/wai-project-comic-books/src/web/static/xml/komiksy.xml
<?xml version="1.0" encoding="utf-8"?>
<comics language="en" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="komiksy_schema.xsd">
	<heroes>
		<hero brand="Marvel Comics">
			<name>Spider-Man</name>
			<superpower>Superhuman agility and strength, spider sense</superpower>
			<image source="https://upload.wikimedia.org/wikipedia/en/thumb/2/21/Web_of_Spider-Man_Vol_1_129-1.png/250px-Web_of_Spider-Man_Vol_1_129-1.png"></image>
			<introduction>
				<date>August 1962</date>
				<age>Silver Age</age>
			</introduction>
		</hero>
		<hero brand="DC Comics">
			<name>Superman</name>
			<superpower>Flying, superhuman strength, speed, indestructibility and many more</superpower>
			<image source="https://upload.wikimedia.org/wikipedia/en/3/35/Supermanflying.png"></image>
			<introduction>
				<date>June 1938</date>
				<age>Golden Age</age>
			</introduction>
		</hero>
		<hero brand="Marvel">
			<name>Deadpool</name>
			<superpower>Regenerative healing factor</superpower>
			<image source="https://upload.wikimedia.org/wikipedia/en/c/ca/Deadpool.png"></image>
			<introduction>
				<date>February 1991</date>
				<age>Modern Age</age>
			</introduction>
		</hero>
	</heroes>
	<origin>
		<country origin ="english">
			<name>The USA</name>
			<term>Comic book</term>
		</country>
		<country origin ="non-english">
			<name>Japan</name>
			<term>Manga</term>
		</country>
		<country origin="non-english">
			<name>Italy</name>
			<term>Fumetti</term>
		</country>
	</origin>
	<formats>
		<format most-popular="yes">Comic book</format>
		<format>Gag cartoons</format>
		<format>Comic strip</format>
		<format>Webcomic</format>
	</formats>
	<specialties>
		<writer>
			<job>Scripts the plot, dialogue and action</job>
			<difficulty>7</difficulty>
		</writer>
		<artist>
			<job>Handles the visuals, which include sketching, inking and colouring the work</job>
			<difficulty>10</difficulty>
		</artist>
		<letterer>
			<job>Fills speech balloons and captions with the dialogue and other words meant to be read</job>
			<difficulty>4</difficulty>
		</letterer>
	</specialties>
	<ages>
		<age>
			<name>Golden Age</name>
			<duration>1938 - 1951</duration>
		</age>
		<age>
			<name>Silver Age</name>
			<duration>1956 - 1970</duration>
		</age>
		<age>
			<name>Bronze Age</name>
			<duration>1970 - 1985</duration>
		</age>
		<age>
			<name>Modern Age</name>
			<duration>1985 - 2020</duration>
		</age>
	</ages>
	<favourites>
		<comic title="Deadpool" brand="Marvel" id="1">
			<issues>2 3 5 6 11</issues>
			<author>Brian Posehn</author>
		</comic>
	</favourites>
	<sources>
		Useful websites to learn more about comics:
		<link source="https://www.marvel.com/comics">Marvel Comics</link>
		<link source="https://www.dccomics.com/comics">DC Comics</link>
		<link source="https://marvel.fandom.com/wiki/Marvel_Database">Marvel Fandom</link>
	</sources>
</comics>
